const titulosCartoes = [
    "Para alguém especial!",
    "Com todo o meu carinho!",
    "Um presente inesquecível!",
    "Para o amor da minha vida!",
    "Feliz aniversário!",
    "Comemore este dia!",
    "Uma lembrança só para você!",
    "Momentos que importam!",
    "Para quem amo muito!",
    "Você merece o melhor!",
    
    // --- Aniversários ---
    "Feliz aniversário, parabéns!",
    "Mais um ano de alegrias!",
    "Um brinde ao seu dia!",
    "Muita saúde e felicidade!",
    "Celebre a vida!",
    "Seu dia chegou!",
    "Sorrisos sem fim hoje!",
    "Desejo tudo de bom!",
    "Parabéns pelo seu dia!",
    "Que venham muitos anos!",
    "Muita luz no seu caminho!",
    "Feliz nova jornada!",
    "Que todos os sonhos se realizem!",
    "Hoje é só festa!",
    "Mais um ciclo de vitórias!",
    "Seu dia, sua alegria!",
    "Comemore intensamente!",
    "Parabéns com muito carinho!",
    "Um novo ano começa hoje!",
  
    // --- Casamentos ---
    "Viva o amor!",
    "Para sempre juntos!",
    "Um brinde aos noivos!",
    "Felizes para sempre!",
    "Celebrando o amor verdadeiro!",
    "Uma nova jornada começa!",
    "Com amor e alegria!",
    "Que seja eterno!",
    "O dia mais especial!",
    "O início de uma linda história!",
    "Um sim para a vida inteira!",
    "Unidos pelo amor!",
    "Que a felicidade acompanhe vocês!",
    "O começo de um lindo capítulo!",
    "Dois corações, uma só vida!",
    "Amor que dura para sempre!",
    "Eternamente felizes!",
    "Casamento dos sonhos!",
    "Lembrança do grande dia!",
  
    // --- Namoro e Amor ---
    "Com amor, sempre!",
    "Para minha alma gêmea!",
    "Você é meu tudo!",
    "Momentos com você!",
    "Cada dia mais amor!",
    "Meu coração é seu!",
    "Sempre ao seu lado!",
    "Você me completa!",
    "Para minha paixão!",
    "Um presente cheio de amor!",
    "Você é meu sorriso!",
    "Meu eterno namorado(a)!",
    "Nosso amor é único!",
    "Com você tudo faz sentido!",
    "O amor da minha vida!",
    "Para minha metade perfeita!",
    "Lembrança de nós dois!",
    "Meu porto seguro!",
    "Para o meu eterno amor!",
    "Um gesto de carinho!",
  
    // --- Datas Especiais ---
    "Boas festas!",
    "Feliz Natal!",
    "Próspero Ano Novo!",
    "Páscoa feliz!",
    "Um dia especial merece um presente!",
    "Celebre cada conquista!",
    "Feliz dia das mães!",
    "Feliz dia dos pais!",
    "Feliz dia dos namorados!",
    "Um presente para hoje!",
    "Feliz dia da amizade!",
    "Para o seu dia especial!",
    "Feliz bodas de casamento!",
    "Um brinde à vida!",
    "Comemorando juntos!",
    "Dia especial merece carinho!",
    "Um presente diferente!",
    "Feliz dia da mulher!",
    "Feliz dia do professor!",
    "Homenagem ao seu dia!",
  
    // --- Gratidão e Amizade ---
    "Obrigado por tudo!",
    "Gratidão infinita!",
    "Você é incrível!",
    "Uma amizade verdadeira!",
    "Você é especial para mim!",
    "Com carinho e amizade!",
    "Um gesto de gratidão!",
    "Para um grande amigo!",
    "Com apreço e alegria!",
    "Sua amizade vale ouro!",
    "Amigos para sempre!",
    "Obrigado pela sua presença!",
    "Você fez a diferença!",
    "Presente de gratidão!",
    "Você é insubstituível!",
    "Meu amigo especial!",
    "Agradeço de coração!",
    "Você merece este carinho!",
    "Um obrigado sincero!",
    "Para alguém muito querido!",
  
    // --- Genéricos e criativos ---
    "Surpresa especial!",
    "De coração para você!",
    "Você merece este presente!",
    "Algo só seu!",
    "Uma lembrança cheia de carinho!",
    "Doce surpresa!",
    "Você é único(a)!",
    "Para iluminar seu dia!",
    "De mim para você!",
    "Porque você merece sorrir!",
    "Detalhes que fazem diferença!",
    "Um carinho inesperado!",
    "Para alegrar sua vida!",
    "Você é importante!",
    "Alegria em forma de presente!",
    "Pequenos gestos, grandes sentimentos!",
    "Que este presente traga sorrisos!",
    "Surpreenda-se hoje!",
    "Com toda minha dedicação!",
  
    // --- Extras para completar até 200 ---
    "Presente cheio de emoção!",
    "Carinho em cada detalhe!",
    "Você merece ser celebrado!",
    "Uma surpresa inesquecível!",
    "Presente com afeto!",
    "De todo coração!",
    "Mais que especial!",
    "Alegria só para você!",
    "Sorrisos garantidos!",
    "Você merece felicidade!",
    "Carinho eterno!",
    "Presente inesquecível!",
    "Doce carinho para você!",
    "Momentos de felicidade!",
    "Celebre cada instante!",
    "Uma lembrança feliz!",
    "Tudo de melhor para você!",
    "Um gesto de amor!",
    "Você merece ser lembrado!",
    "Para eternizar momentos!",
    "Lembrança carinhosa!",
    "Para aquecer o coração!",
    "Carinho e dedicação!",
    "Você é muito especial!",
    "Que seja um dia feliz!",
    "Presentes que marcam!",
    "Para sorrir sempre!",
    "Um abraço em forma de presente!",
    "Você é inesquecível!",
    "Desejo de felicidade!",
    "Com todo o carinho do mundo!",
    "Um presente diferente e único!",
    "Especial como você!",
    "Um mimo cheio de afeto!",
    "Lembrança cheia de ternura!",
    "Você merece carinho!",
    "Sorrisos em abundância!",
    "Para tornar o dia especial!",
    "Um presente feito com amor!",
    "Que este gesto aqueça sua alma!",
    "Um mimo só seu!",
    "Alegrias infinitas!",
    "Lembrança inesquecível!",
    "Um presente simbólico!",
    "Um carinho para sempre!",
    "Você merece alegria!",
    "De coração aberto!",
    "Um gesto inesquecível!",
    "Com ternura e carinho!",
    "Pequeno gesto, grande significado!",
    "Carinho em forma de cartão!",
    "Um presente que emociona!",
    "Detalhe que faz diferença!",
    "Com amor e amizade!",
    "Um gesto especial para você!",
    "Presente de todo coração!",
    "Para celebrar a vida!",
    "Alegria hoje e sempre!",
    "Você é inesquecível para mim!",
    "Com carinho sincero!",
    "Surpresa cheia de amor!",
    "Pequeno, mas especial!",
    "Para guardar no coração!",
    "Presente simbólico de carinho!",
    "Para tornar o dia melhor!",
    "Um gesto para lembrar!",
    "Sorrisos sem fim!",
    "Alegria no seu caminho!",
    "Você merece o mundo!",
    "Presente eterno!",
    "Um gesto singelo!",
    "Para alegrar seu coração!",
    "Você é lembrado com carinho!",
    "Para encher sua vida de alegria!",
    "Um presente inesquecível para você!",
    "Presente que vem do coração!",
    "Detalhes que encantam!",
    "Um gesto cheio de amor!",
    "Para momentos felizes!",
    "Você é uma bênção!",
    "Um presente só seu!",
    "Um carinho inesperado!",
    "Você faz parte da minha vida!",
    "Presente de afeto!",
    "Para alegrar o dia!",
    "Surpresa inesquecível!",
    "Um gesto pequeno, mas valioso!",
    "Você é uma estrela!",
    "De presente para presente!",
    "Para eternizar este momento!",
    "Presente feito para você!",
    "Carinho sem limites!",
    "Um detalhe cheio de amor!",
    "Você merece mais!",
    "Para encher o coração de alegria!",
    "Com carinho verdadeiro!",
    "Um gesto eterno!",
    "Alegria que contagia!",
    "Um presente feito de amor!",
    "Você é especial demais!",
    "Para você sorrir hoje!",
    "Presente inesquecível para alguém único!",
    "Um gesto de ternura!",
    "Você ilumina meu mundo!",
    "Presente cheio de magia!",
    "Para celebrar nossa amizade!",
    "Um presente marcante!",
    "Para minha pessoa favorita!",
    "Você é meu maior presente!",
    "De presente para vida!",
    "Para eternizar lembranças!",
    "Presente de felicidade!",
    "Para alguém incrível!",
    "Você merece o melhor de mim!",
    "Um carinho para sua vida!",
    "Um presente cheio de significado!",
    "Você faz parte da minha história!",
    "Presente inesquecível com amor!",
    "Um gesto de lembrança!",
    "Para espalhar alegria!",
    "Você é único no mundo!",
    "Presente que aquece o coração!",
    "Para meu amor eterno!",
    "Carinho para sempre!",
    "Você merece todos os sorrisos!",
    "Um gesto de alegria!",
    "Presente com muita emoção!",
    "Para meu melhor amigo!",
    "Um presente de coração!",
    "Carinho em forma de lembrança!",
    "Você é um presente para mim!",
    "Com amor eterno!",
    "Um gesto especial de carinho!",
    "Presente que transmite afeto!",
    "Para celebrar este dia lindo!"
  ];
  
export const gerarTituloCartao = (): string => {
    const indice = Math.floor(Math.random() * titulosCartoes.length);
    return titulosCartoes[indice];
}
