const mensagensEspeciais = [
    'Hoje não é uma data comemorativa ou especial, mas você é uma pessoa especial, então estou vindo aqui para dizer o quanto gosto de você. Tenho um carinho enorme e gratuito pela sua pessoa, e acho que você deveria saber disso. Você já foi meu ombro amigo e ouvinte vezes suficientes para eu saber que posso contar com você, e saiba que a recíproca é verdadeira. Te adoro!',    
    'Hoje, queria te dizer o quanto você é especial para mim. Desde o primeiro dia em que nos conhecemos, você trouxe luz e alegria à minha vida. Sua presença me envolve com carinho e ternura, tornando cada momento ao seu lado memorável. Mesmo nas adversidades, sei que posso contar com você. Sua presença traz conforto e esperança, e me faz acreditar que tudo ficará bem. Sua força e coragem me inspiram a ser uma pessoa melhor a cada dia.',
    'Eu não tenho sequer palavras para poder expressar minha gratidão por te ter na minha vida. Não é todo dia que conhecemos uma pessoa tão alegre, solar e iluminada como você. Alguém que está sempre com disposição para ajudar os outros, com sorriso no rosto, não importa o que aconteça. Você é uma inspiração para mim! Continue sempre brilhando e espalhando seu amor por onde passar, e que o universo te recompense por toda sua bondade! Grande abraço!',
    'Oi! Hoje não é nenhuma ocasião especial, mas, mesmo assim, decidi escrever a você esta mensagem para demonstrar o meu carinho e o quanto amo a sua pessoa! Minha vida certamente não teria sido tão boa até aqui se não fosse a presença de pessoas especiais como você. Espero que todos esses anos de presença sejam apenas o início de uma linda história que vamos compartilhar e de um longo caminho que vamos dividir.',
    'Sinta o meu amor te tocar com o meu carinho. Não, não é só do carinho físico que digo. É, também, do sentimento de carinho, compaixão e afeto. Sinta o meu amor porque você é amado(a).',
    'Não devemos esperar para expressar nosso carinho por pessoas especiais, pois nunca sabemos o dia de amanhã. No momento em que uma pessoa querida passa pela nossa mente, é importante entrar em contato, mesmo que seja para mandar uma simples mensagem, por isso envio-lhe esse recado agora. Você é aquela pessoa com a qual posso contar e meu respeito por você cresce a cada dia.',
    'Ei, eu te amo! Não se esqueça disso, tá? Muitas vezes, a vida vai passando bem rapidinho, aí a gente se esquece de dizer para as pessoas queridas que elas são tão amadas. Mas existe em mim uma determinação para evitar que isso aconteça, por isso decidi escrever esta mensagem, com o objetivo de demonstrar para você o quanto gosto de ti e o quanto a sua presença definitivamente faz diferença na minha vida. Que estejamos juntos sempre!',
    'Nossa conexão foi espontânea e instantânea. Poucas palavras bastaram pra gente perceber que tem muito em comum e que o carinho entre a gente seria mútuo. Gosto muito dessa sementinha que foi regada entre nós e que agora enraizou, floresceu e se consolidou. Você é uma pessoa que merece todos os elogios do mundo! Admiro demais sua força e seu jeito de levar a vida. Eu aprendo muito convivendo com você.',
    'Estou passando para dizer que você é uma das pessoas mais importantes que existe. Sem o seu carinho e o seu amor, minha vida seria extremamente vazia e sem sentido. Ao seu lado, meus dias são mais completos e infinitamente mais bonitos, pois seu sorriso e sua companhia fazem meu coração transbordar de alegria. Espero que essas palavras cheguem até você como o mais carinhoso dos abraços!',
    'Você não faz ideia do impacto que tem na minha vida, pois a sua mera presença já é o suficiente para suscitar imensa gratidão do meu coração e me fazer esboçar um sorriso, automaticamente e sem nem perceber. Você merece saber do carinho que sinto por você, para que você nunca se esqueça do seu valor e de suas indiscutíveis qualidades. Espero sempre ter a sorte de tê-la por perto!',
    'Carinho diz muito sobre uma pessoa. Para quem recebe, quer dizer que ela é tão amada ou apreciada por alguém que foi preciso externar o sentimento. É uma posição de honra, tendo em vista que gestos como esse são raros no nosso dia. Já para quem oferece é uma forma de demonstrar tudo aquilo que está sentindo de uma forma delicada. Torna-se um ato nobre e corajoso, afinal muitas pessoas acabaram perdendo a sensibilidade para demonstrar sua emoção.',
    'Tenho um carinho por você que não cabe dentro do meu pequeno coração. Cultivo em mim esse vasto afeto pela pessoa que você é para o mundo e que representa para mim. Sua generosidade me encanta, sua bondade me inspira, suas palavras me fortalecem e sua crença me faz acreditar. É bom demais estar ao lado de quem te faz acreditar nas coisas. É amor puro. Que o mundo seja gentil com você para que você continue sendo sempre assim: incrível.',
    'A palavra carinho, segundo o dicionário, quer dizer uma demonstração afetuosa de amor ou apreço, que pode conter contato físico ou não. Por meio desse gesto é que manifestamos nossa consideração por alguém, lembrando que cada pessoa tem seu modo de exprimir sentimentos. Revelar seu jeito carinhoso de ser não só mostra que você é uma pessoa amorosa, mas um ser humano que não tem medo de expor suas emoções e emanar coisas boas.',
    'Você cultivou em meu coração tantas coisas boas e o regou com tanto amor que, hoje, consigo enxergar os frutos desse cuidado. Você é essencial em minha vida e jamais esquecerei o que fez por mim. Eu o amo e terei eterna gratidão a você, que viu e enxergou em mim uma esperança que estava adormecida. Conte comigo para o que precisar, não tenho dúvidas de que não há nada capaz de destruir essa ponte que construímos juntos.',
    'Não tenha medo de ser exatamente quem você é. O que você tem de diferente dos outros é exatamente aquilo que te torna uma pessoa tão bela. A insegurança é somente uma voz inconveniente que faz você acreditar no que não é real. Respire fundo, viva um dia por vez e permita-se ser feliz. Ainda que os meus braços não possam te alcançar neste momento, o meu coração te abraça com todo o carinho!',
    'Você já deve ter percebido que nem tudo se compra com o dinheiro. O verdadeiro sentido da vida está nos pequenos encontros, nos mínimos gestos, na espontaneidade de um sorriso... você faz parte do todo. Você importa! Você faz a diferença. Seja gentil com o próximo durante toda a sua jornada, pois, assim como você, cada pessoa está enfrentando uma batalha que só ela mesma pode mensurar. Não se esqueça: enquanto o bem existir, o mal jamais prevalecerá.',
    'O que seria do mundo sem carinho? E como seria se você não estivesse aqui com toda a afeição que você tem para dar? Quero que saiba que é uma pessoa muito especial para todos ao seu redor, jamais se esqueça disso! Estar ao seu lado é aprender todos os dias a amar, ser grato, ser feliz e ser uma pessoa melhor. Como é bom tê-la por perto todos os dias. Escrevo isso a você com todo o amor do mundo. Não se esqueça que eu amo você.',
    'Cada dia ao seu lado é como uma nova página de um livro mágico e apaixonante! Seu sorriso ilumina meu mundo e seu abraço é meu refúgio. Quando estamos lado a lado, sinto que posso conquistar qualquer coisa, seja ela qual for!'
]

export const gerarMensagemEspecial = (): string => {
    const indice = Math.floor(Math.random() * mensagensEspeciais.length);
    return mensagensEspeciais[indice];
}